# -*- coding: utf-8 -*-
"""Cópia de Atividade APIS Joao_Meireles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3kgTHP_tY2b2vBIi8mXbtUlJ5hiEnTh

# TEMPLATE

Template base para elaboração na atividade. Execute todas as células a seguir para garantir o funcionamento de sua API (app).
"""

!pip install -q fastapi uvicorn nest-asyncio pyngrok

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional
import uvicorn
import nest_asyncio
from typing import List
import threading
from pyngrok import ngrok
from fastapi import Header
from typing import Optional
from jose import jwt
from datetime import datetime, timedelta
from fastapi.security import HTTPBearer
from fastapi import FastAPI, HTTPException, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

from pydantic import BaseModel

from jose import jwt, JWTError

from datetime import datetime, timedelta

from typing import Optional

app = FastAPI(
    title="Book API",
    description="API de Gerenciamento de uma Biblioteca.",
    version="1.0.0",
)



"""Crie sua chave em https://dashboard.ngrok.com/"""

!ngrok config add-authtoken 3CxFdVkO6xpV7ln3pfhi9Pk1nO2_48LyamR38kM6uaQNT1nh4

if __name__ == "__main__":
    nest_asyncio.apply()
    def rodar_servidor():
        uvicorn.run(app, host="0.0.0.0", port=8000)

    thread = threading.Thread(target=rodar_servidor, daemon=True)
    thread.start()

    url_publica = ngrok.connect(8000)
    print(f"\nAPI disponível em: {url_publica}")

"""# SEU CÓDIGO A PARTIR DAQUI"""

SECRET_KEY = "biblioteca"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
security = HTTPBearer()



class Login(BaseModel):
    username: str
    password: str

class LivroCreate(BaseModel):
    titulo: str
    autor: str
    categoria: str
    ano: int

class LivroResponse(BaseModel):
    id: int
    titulo: str
    autor: str
    categoria: str
    ano: int
    disponivel: bool
    emprestado_para: Optional[int]

class UsuarioCreate(BaseModel):
    nome: str
    email: str
    matricula: str

class UsuarioResponse(BaseModel):
    id: int
    nome: str
    email: str
    matricula: str
    livros_emprestados: int

class Emprestimo(BaseModel):
    usuario_id: int
    livro_id: int

livros = [

    {
        "id": 1,
        "titulo": "Clean Code",
        "autor": "Robert Martin",
        "categoria": "Programação",
        "ano": 2008,
        "disponivel": True,
        "emprestado_para": None
    },

    {
        "id": 2,
        "titulo": "Dom Casmurro",
        "autor": "Machado de Assis",
        "categoria": "Literatura",
        "ano": 1899,
        "disponivel": True,
        "emprestado_para": None
    }

]

usuarios = [

    {
        "id": 1,
        "nome": "João Pedro",
        "email": "joao@email.com",
        "matricula": "2023001",
        "livros_emprestados": 0
    },

    {
        "id": 2,
        "nome": "Maria Oliveira",
        "email": "maria@email.com",
        "matricula": "2023002",
        "livros_emprestados": 0
    }

]
# Token de administrador
admin = {
    "username": "admin",
    "password": "123"
}


def criar_token(username: str):

    expire = datetime.utcnow() + timedelta(
        minutes=ACCESS_TOKEN_EXPIRE_MINUTES
    )

    payload = {
        "sub": username,
        "exp": expire
    }

    token = jwt.encode(
        payload,
        SECRET_KEY,
        algorithm=ALGORITHM
    )

    return token

@app.post("/login")
def login(dados: Login):

    if (
        dados.username != admin["username"]
        or
        dados.password != admin["password"]
    ):

        raise HTTPException(
            status_code=401,
            detail="Credenciais inválidas"
        )

    token = criar_token(
        dados.username
    )

    return {
        "access_token": token
    }

  #Funcao verificar Tokens
def verificar_token(
    credentials:
    HTTPAuthorizationCredentials =
    Depends(security)
):

    token = credentials.credentials

    try:

        payload = jwt.decode(
            token,
            SECRET_KEY,
            algorithms=[ALGORITHM]
        )

        return payload

    except JWTError:

        raise HTTPException(
            status_code=401,
            detail="Token inválido"
        )
# Endpoint para cadastrar livros
@app.post("/livros")
def cadastrar_livro(livro: LivroCreate,token: dict =Depends(verificar_token)):
# Verifica se o livro já existe
    for item in livros:

        if (
            item["titulo"].lower() == livro.titulo.lower()
            and item["autor"].lower() == livro.autor.lower()
        ):

            raise HTTPException(
                status_code=400,
                detail="Livro já cadastrado"
            )
    novo_livro = {
        "id": len(livros) + 1,
        "titulo": livro.titulo,
        "autor": livro.autor,
        "categoria": livro.categoria,
        "ano": livro.ano
    }

    livros.append(novo_livro)

    return {
        "mensagem": "Livro cadastrado com sucesso",
        "livro": novo_livro
    }
# Endpoint para listar usuários

@app.get("/usuarios")
def listar_usuarios(token: dict =Depends(verificar_token)):

    return {

        "quantidade": len(usuarios),

        "usuarios": usuarios
    }

# Endpoint para listar livros

@app.get("/livros")
def listar_livros():

    return {

        "quantidade": len(livros),

        "livros": livros
    }
# Endpoint para cadastrar usuários

@app.post("/usuarios")
def cadastrar_usuario(

    usuario: UsuarioCreate,

    token: dict =
    Depends(verificar_token)

):

    # Verifica email duplicado

    for item in usuarios:

        if (

            item["email"].lower()
            ==
            usuario.email.lower()

        ):

            raise HTTPException(

                status_code=400,

                detail=
                "Usuário já cadastrado"
            )

    # Cria usuário

    novo_usuario = {

        "id": len(usuarios) + 1,

        "nome": usuario.nome,

        "email": usuario.email,

        "matricula": usuario.matricula,

        "livros_emprestados": 0
    }

    # Adiciona lista

    usuarios.append(novo_usuario)

    # Retorno

    return {

        "mensagem":
        "Usuário cadastrado com sucesso",

        "usuario":
        novo_usuario
    }
# Endpoint para realizar empréstimo

@app.post("/emprestimos")
def realizar_emprestimo(

    emprestimo: Emprestimo,

    token: dict =
    Depends(verificar_token)

):

    # =========================
    # PROCURA LIVRO
    # =========================

    livro_encontrado = None

    for livro in livros:

        if (

            livro["id"]
            ==
            emprestimo.livro_id

        ):

            livro_encontrado = livro

    # =========================
    # VALIDA LIVRO
    # =========================

    if livro_encontrado is None:

        raise HTTPException(

            status_code=404,

            detail=
            "Livro não encontrado"
        )

    # =========================
    # VERIFICA DISPONIBILIDADE
    # =========================

    if not livro_encontrado["disponivel"]:

        raise HTTPException(

            status_code=400,

            detail=
            "Livro indisponível"
        )

    # =========================
    # PROCURA USUÁRIO
    # =========================

    usuario_encontrado = None

    for usuario in usuarios:

        if (

            usuario["id"]
            ==
            emprestimo.usuario_id

        ):

            usuario_encontrado = usuario

    # =========================
    # VALIDA USUÁRIO
    # =========================

    if usuario_encontrado is None:

        raise HTTPException(

            status_code=404,

            detail=
            "Usuário não encontrado"
        )

    # =========================
    # REALIZA EMPRÉSTIMO
    # =========================

    livro_encontrado["disponivel"] = False

    livro_encontrado["emprestado_para"] = (

        emprestimo.usuario_id
    )

    # =========================
    # ATUALIZA USUÁRIO
    # =========================

    usuario_encontrado[
        "livros_emprestados"
    ] += 1

    # =========================
    # RETORNO
    # =========================

    return {

        "mensagem":
        "Empréstimo realizado com sucesso",

        "livro":
        livro_encontrado,

        "usuario":
        usuario_encontrado
    }

@app.put("/devolucao/{id}")
def devolver_livro(

    id: int,

    token: dict =
    Depends(verificar_token)

):

    # =========================
    # PROCURA LIVRO
    # =========================

    livro_encontrado = None

    for livro in livros:

        if livro["id"] == id:

            livro_encontrado = livro

    # =========================
    # VALIDA LIVRO
    # =========================

    if livro_encontrado is None:

        raise HTTPException(

            status_code=404,

            detail=
            "Livro não encontrado"
        )

    # =========================
    # VERIFICA SE ESTÁ EMPRESTADO
    # =========================

    if livro_encontrado["disponivel"]:

        raise HTTPException(

            status_code=400,

            detail=
            "Livro já está disponível"
        )

    # =========================
    # PROCURA USUÁRIO
    # =========================

    usuario_encontrado = None

    for usuario in usuarios:

        if (

            usuario["id"]
            ==
            livro_encontrado["emprestado_para"]

        ):

            usuario_encontrado = usuario

    # =========================
    # DEVOLVE LIVRO
    # =========================

    livro_encontrado["disponivel"] = True

    livro_encontrado["emprestado_para"] = None

    # =========================
    # ATUALIZA USUÁRIO


    if usuario_encontrado is not None:

        usuario_encontrado[
            "livros_emprestados"
        ] -= 1

    # =========================
    # RETORNO
    # =========================

    return {

        "mensagem":
        "Livro devolvido com sucesso",

        "livro":
        livro_encontrado,

        "usuario":
        usuario_encontrado
    }